config/routes.rb
Rails.application.routes.draw do
  #get 'password_resets/new'

  #get 'password_resets/edit'

  #get 'sessions/new'

  #get 'users/new'

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'new_match' => 'matches#new'

  get 'open' => 'matches#open'

  get 'challenges' => 'matches#challenges'


  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only:  [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :matches do
    member do
      get :join
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @feed_items = current_user.feed.where("p2Active = ? AND p3Active = ? AND p4Active = ?", 1, 1, 1).where(time: 10.years.ago..1.month.from_now).paginate(page: params[:page]).order(time: :desc)
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="center jumbotron">

<h1>About</h1>
	<p>
		This is the page about the website.
	</p>

</div>

app/views/static_pages/contact.html.erb
<div class="center jumbotron">

	<h1>Contact</h1>
	<p>
		This is the contact page.
	</p>

</div>

app/views/static_pages/help.html.erb
<h1>Help Page</h1>
	<p>
	CONTENTS OF THE HELP PAGE
	</p>

app/views/static_pages/home.html.erb
<div class="jumbotron">
	<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section>
        <h1>
          <%= gravatar_for current_user %>
          <%= current_user.name %>
        </h1>
      </section>

      <section class="stats">
        <%= render 'shared/stats' %>
      </section>

      <section class="user_stats">
        <%= render 'shared/user_stats' %>
      </section>

    </aside> 
    <div class="col-md-8">
    <%= link_to "Create a Match", new_match_path, class: "btn btn-primary" %>
    <%= link_to "View Challenges", challenges_path, class: "btn btn-primary" %>
      <h3>Match Feed</h3>
      <%= render 'shared/feed' %>
    </div>

    <% else %>
    <div align = "center">
  		<link href='http://fonts.googleapis.com/css?family=Playfair+Display+SC:900italic' rel='stylesheet' type='text/css'><h1>Game! Set! Play!</h1>
  		<h2>
  			Welcome to GameSetPlay!!
  		</h2>

  		<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>

  		<%= link_to "Log In!", login_path, class: "btn btn-lg btn-primary" %>
     <% end %>
    </div>
  </div>