config/routes.rb
Rails.application.routes.draw do
  #get 'password_resets/new'

  #get 'password_resets/edit'

  #get 'sessions/new'

  #get 'users/new'

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'new_match' => 'matches#new'

  get 'open' => 'matches#open'

  get 'challenges' => 'matches#challenges'


  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only:  [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :matches do
    member do
      get :join
    end
  end
end

app/models/match.rb
class Match < ActiveRecord::Base
	has_many :user_matches
	has_many :users, through: :user_matches
	
	validates :player1, presence: true
	validates :location, presence: true
	validates :time, presence: true
	validates :game_type, presence: true
	validates :open, presence: true
	validates :zip, presence: true

	after_initialize :defaults

    def defaults

	      self.player2 ||= 'Player 2' 

	      self.player3 ||= 'Player 3'

	      self.player4 ||= 'Player 4'

        self.p2Active ||= 0

        self.p3Active ||= 0

        self.p4Active ||= 0

        self.scoreValid ||= 0

        self.validated ||= 3

    end

    def self.search(query1, query2, query3, query4)
    	@query2 = query2
    	@creator = User.find_by(name: "#{@query2}")

      #Have to catch in case of nil.
  		if (query1 != "" && query2 != "" && query3 != "" && query4 != "") #A user uses all search criteria.
  				where("game_type like ? AND player1 like ? AND zip like ? AND time like ?", "%#{query1}%", User.find_by(name: "#{query2}").id, "%#{query3}%", "%#{query4}%")

  		elsif (query1 != "" && query2 == "" && query3 == "" && query4 == "") #A user searches for a match by type.
  			where("game_type like ?", "%#{query1}%")
  		
  		elsif (query1 == "" && query2 != "" && query3 == "" && query4 == "") #A user searches for a match by creator
  			where("player1 like ?", User.find_by(name: "#{query2}").id)
  		
  		elsif (query1 == "" && query2 == "" && query3 != "" && query4 == "") #A user searches for a match by zip.
  			where("zip like ?", "%#{query3}%")
  		
  		elsif (query1 == "" && query2 == "" && query3 == "" && query4 != "") #A user searches for a match by date.
  			where("time like ?", "%#{query4}%")

  		elsif (query1 != "" && query2 != "" && query3 == "" && query4 == "") #A user searches for a match by type and creator.
  			where("game_type like ? AND player1 like ?", "%#{query1}%", User.find_by(name: "#{query2}").id)
  		
  		elsif (query1 != "" && query2 == "" && query3 != "" && query4 == "") #A user searches for a match by type and zip.
  			where("game_type like ? AND zip like ?", "%#{query1}%", "%#{query3}%")

  		elsif (query1 == "" && query2 != "" && query3 != "" && query4 == "") #A user searches for a match by creator and zip.
  			where("player1 like ? AND zip like ?", User.find_by(name: "#{query2}").id, "%#{query3}%")

  		elsif (query1 != "" && query2 == "" && query3 == "" && query4 != "") #A user searches for a match by type and date.
  			where("game_type like ? AND zip like ?", "%#{query1}%", "%#{query3}%")
  		
  		elsif (query1 == "" && query2 != "" && query3 == "" && query4 != "") #A user searches for a match by creator and date.
  			where("player1 like ? AND time like ?", User.find_by(name: "#{query2}").id, "%#{query4}%")
  		
  		elsif (query1 == "" && query2 == "" && query3 != "" && query4 != "") #A user searches for a match by zip and date.
  			where("zip like ? AND time like ?", "%#{query3}%", "%#{query4}%")

  		elsif (query1 != "" && query2 != "" && query3 != "" && query4 == "") #A user searches for a match by type, creator and zip. 
  			where("game_type like ? AND player1 like ? AND zip like ?", "%#{query1}%", User.find_by(name: "#{query2}").id, "%#{query3}%")

  		elsif (query1 != "" && query2 == "" && query3 != "" && query4 != "") #A user searches for a match by type, zip and date.
  			where("game_type like ? AND zip like ? AND time like ?", "%#{query1}%", "%#{query3}%", "%#{query4}%")

  		elsif (query1 != "" && query2 != "" && query3 == "" && query4 != "") #A user searches for a match by type, creator and date.
  			where("game_type like ? AND player1 like ? AND time like ?", "%#{query1}%", User.find_by(name: "#{query2}").id, "%#{query4}%")
  		
  		elsif (query1 == "" && query2 != "" && query3 != "" && query4 != "") #A user searches for a match by creator, zip and date.
  			where("player1 like ? AND zip like ? AND time like ?", User.find_by(name: "#{query2}").id, "%#{query3}%", "%#{query4}%")

  		else
      		where("open = ?", 1)
      	end

	end

	# Sends challenge email.
	def send_challenge_email(opponent, match, challenger)
	  @opponent = opponent
    @match = match
    @challenger = challenger
	  MatchMailer.matchEmail(@opponent, @match, @challenger).deliver_now
	end

  # Sends an email to the match creator letting him or her know a match was declined.
  def send_decline_email(creator, match)
    @user = creator
    @match = match
    MatchMailer.declineEmail(@user, @match).deliver_now
  end

  # Sends an email for singles' score validation.
  def send_validation_email(player, match)
    @user = player
    @match = match
    MatchMailer.validationEmail(@user, @match).deliver_now
  end

  # Sends an email in the event of an invalid score.
  def send_invalid_score_email(player, match)
    @user = player
    @match = match
    MatchMailer.invalidScoreEmail(@user, @match).deliver_now
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
	
	def new
  	  @match = Match.new
    end

    def index
	   @matches = Match.paginate(page: params[:page])
	end

	def show
	  @match = Match.find_by(id: params[:id])
	end

	def edit
		@match = Match.find(params[:id])
		@player1 = User.find_by(id: @match.player1)
		@player2 = User.find_by(id: @match.player2)
		@player3 = User.find_by(id: @match.player3)
		@player4 = User.find_by(id: @match.player4)

	end

	def join
		@match = Match.find_by(id: params[:id])
	end

	def challenges
		@user = User.find_by(id: current_user.id)
		@matches = Match.where("p2Active = ? AND player2 = ? OR p3Active = ? AND player3 = ? OR p4Active = ? AND player4 = ?", 0, "#{current_user.id}", 0, "#{current_user.id}", 0, "#{current_user.id}",).paginate(page: params[:page])
	end

	def update
    @match = Match.find(params[:id])
    @id = params[:id]
    @player1 = User.find_by(id: @match.player1)
	@player2 = User.find_by(id: @match.player2)
	@player3 = User.find_by(id: @match.player3)
	@player4 = User.find_by(id: @match.player4)

	    if (@match.update_attributes(match_params))

	    	if (@match.player2 != "Player 2" && @match.player3 != "Player 3" && @match.player4 != "Player 4")
	    		activatePlayers(@id)
	    	end

		    	if (@match.game_type == "Singles" && @player2 != nil && @match.time < Time.now) #Have to differentiate between singles and doubles matches.
					if (@match.scoreValid == 1 && @match.validated == 3) #send an email to the other player requesting validation.
						
						if (@player1.id == current_user.id)
							@match.validator1 == @player2.id
							@match.send_validation_email(@player2, @match) # email sent
							flash[:success] = "Your opponent has been notified."
						else
							@match.validator1 == @player1.id
							@match.send_validation_email(@player1, @match) #email sent
							flash[:success] = "Your opponent has been notified."
						end

					elsif (@match.scoreValid == 4 && @match.validator1 == current_user.id)  #The scores entered are valid
							if (@match.validated == 1)
							    if (@match.winner == @player1.name) #Player one is the winner
							    	updateWinner(@match.player1)
							    	updateLoser(@match.player2)
							    	flash[:success] = "Scores updated. Congratulations #{@match.winner}!!"
							    else #Player two is the winner.
							    	updateWinner(@match.player2)
							    	updateLoser(@match.player1)
							    	flash[:success] = "Scores updated. Congratulations #{@match.winner}!!"
							    end
							elsif (@match.validated == 0)
								#Send an email to the both players and increase both player's invalid score count by one.
								@match.send_invalid_score_email(@player1, @match) #email sent
								@match.send_invalid_score_email(@player2, @match) #email sent
								updateInvalids(@match.player1)
								updateInvalids(@match.player2)
								flash[:danger] = "Your opponent has been notified of the invalid scores."
							end	
						
					end
				elsif (@match.game_type == "Doubles" && @player2 != nil && @player3 != nil && @player4 != nil && @match.time < Time.now)

					if (@match.scoreValid == 1 && @match.validated == 3) #send an email to the other players requesting validation.
						#set @match.validator to each other player's id.
						if (@player1.id == current_user.id || @player2.id == current_user.id)  #Only allow players from the other team to validate scores.
							@match.send_validation_email(@player3, @match) #email sent
							@match.send_validation_email(@player4, @match) #email sent
							flash[:success] = "Your opponents have been notified."
						elsif (@player3.id == current_user.id || @player4.id == current_user.id)
							@match.send_validation_email(@player2, @match) #email sent
							@match.send_validation_email(@player1, @match) #email sent
							flash[:success] = "Your opponents have been notified."
						end
					elsif (@match.scoreValid == 4 && (@match.validator1 == current_user.id || @match.validator2 == current_user.id || @match.validator3 == current_user.id)) #The scores entered are valied
						if (@match.validated == 1)
							if (@match.winner == "#{@player1.name} & #{@player2.name}") #The creator of the match and his or her partner won.
								updateWinner(@match.player1)
								updateWinner(@match.player2)
								updateLoser(@match.player3)
								updateLoser(@match.player4)
								flash[:success] = "Scores updated. Congratulations #{@match.winner}!!"
							else #The opponents won.
								updateWinner(@match.player4)
								updateWinner(@match.player3)
								updateLoser(@match.player2)
								updateLoser(@match.player1)
								flash[:success] = "Scores updated. Congratulations #{@match.winner}!!"
							end
						elsif (@match.validated == 0)
							# Send an email to the match creator and increase all player's invalid score count by one.
							@match.send_invalid_score_email(@player1, @match) #email sent
							@match.send_invalid_score_email(@player2, @match) #email sent
							@match.send_invalid_score_email(@player3, @match) #email sent
							@match.send_invalid_score_email(@player4, @match) #email sent
							updateInvalids(@match.player1)
							updateInvalids(@match.player2)
							updateInvalids(@match.player3)
							updateInvalids(@match.player4)
							flash[:danger] = "The other players have been notified of the invalid scores."
						end
					end
				elsif (@match.player2Accept == 0 || @match.player3Accept == 0 || @match.player4Accept == 0)
					flash[:danger] = "You have declined the challenge.  The match creator has been notified."
					@match.send_decline_email(@player1, @match)

				elsif (@match.player2 == @match.player3)
	    			flash[:danger] = "You cannot join as both a partner and an opponent."
	    			fixPlayers1(@match)
	    		elsif (@match.player2 == @match.player4)
	    			flash[:danger] = "You cannot join as both a partner and an opponent."
	    			fixPlayers2(@match)
				elsif (@match.time > Time.now)
					flash[:success] = "You have been added to the match!  Good luck!"
			end
	   
	      redirect_to root_url
	    else

	      render 'edit'
	    end
	end

	def create
	  @match = Match.new(match_params)
	  @player1 = current_user

	  #Set the variables.
	  @name = @match.player2.titleize
	  @player2 = User.find_by(name: "#{@name}")
	  
	  @name3 = @match.player3.titleize
	  @player3 = User.find_by(name: "#{@name3}")
	  
	  @name4 = @match.player4.titleize
	  @player4 = User.find_by(name: "#{@name4}")
	  
	  @location = @match.location
	  @game_type = @match.game_type
	  @open = @match.open
	  @time = @match.time
	  @zip = @match.zip

	  #Do not allow a match between a user and itslef.
	  if (@player2 == current_user || (( @player3 == current_user || @player4 == current_user) && @game_type == "Doubles"))
	  	flash[:danger] = "You cannot play yourself."
	  	@match.destroy
	  	redirect_to root_url
	  elsif (@player2 == nil && @player3 == nil && @player4 == nil && @open == 0 && @game_type == "Doubles")  #Ensure the user exists in the database.
	  	flash[:danger] = "You must enter other players to create a private doubles match."
	  	@match.destroy
	  	redirect_to root_url
	  elsif (@player2 == nil && @player3 == nil && @open == 0 && @game_type == "Doubles")  #Ensure the user exists in the database.
	  	flash[:danger] = "You must enter a partner and another opponent to create a private doubles match."
	  	@match.destroy
	  	redirect_to root_url
	  elsif (@player2 == nil && @open == 0 && @game_type == "Doubles")  #Ensure the user exists in the database.
	  	flash[:danger] = "Player 2 was not found in our database."
	  	@match.destroy
	  	redirect_to root_url
	  elsif (@player3 == nil && @open == 0 &&@game_type == "Doubles")  #Ensure the user exists in the database.
	  	flash[:danger] = "Player 3 was not found in our database."
	  	@match.destroy
	  	redirect_to root_url
	  elsif (@player4 == nil && @open == 0 && @game_type == "Doubles")  #Ensure the user exists in the database.
	  	flash[:danger] = "Player 4 was not found in our database."
	  	@match.destroy
	  	redirect_to root_url
	  elsif (@player2 == nil && @open == 0)  #Ensure the user exists in the database.
	  	flash[:danger] = "Your opponent was not found in our database."
	  	@match.destroy
	  	redirect_to root_url
	  elsif (@player2 == nil && @name != 'Player 2' && @open == 1 && @game_type == "Doubles")  #Ensure the user exists in the database.
	  	flash[:danger] = "Player 2 was not found in our database."
	  	@match.destroy
	  	redirect_to root_url
	  elsif (@player3 == nil && @name3 != 'Player 3' && @open == 1 &&@game_type == "Doubles")  #Ensure the user exists in the database.
	  	flash[:danger] = "Player 3 was not found in our database."
	  	@match.destroy
	  	redirect_to root_url
	  elsif (@player4 == nil && @name4 != 'Player 4' && @open == 1 && @game_type == "Doubles")  #Ensure the user exists in the database.
	  	flash[:danger] = "Player 4 was not found in our database."
	  	@match.destroy
	  	redirect_to root_url
	  
	  #Create different match types based on the user input.
	  #Singles/Private
	  elsif (@game_type == "Singles" && @open == 0) 
	  	@match = current_user.challenge(@player2, @location, @game_type, @open, @time, @zip) 
			@match.player3 = ""
			@match.player4 = ""
			@match.p3Active = 1
			@match.p4Active = 1
			if @match.save  #match creation
			#Email Setup
		    @match.send_challenge_email(@player2, @match, @player1)
		    flash[:info] = "Your opponent has been notified."
		    redirect_to root_url
		    else
		      @match.player2 = @name
			  render 'new' #In case of errors.
		    end
	   
	   #Singles/Public 
	   elsif (@game_type == "Singles" && @open == 1)
	   	@match = current_user.open_challenge(@location, @game_type, @open, @time, @zip)
       		@match.player3 = ""
       		@match.player4 = ""
       		@match.p3Active = 1
			@match.p4Active = 1
       		if @match.save  #match creation
			#No email since it is an open match.

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_match.html.erb
<li class="matches" id="match-<%= match.id %>"> 
  
  <span class="player1">Player 1: <%= User.find_by(id: [match.player1]).name %></span>
  
    <% if (match.game_type == "Singles" && match.open == 0) %>

      <% if (User.find_by(id: match.player2) != nil) %>
        <span class="player2">Player 2: <%= User.find_by(id: match.player2).name %> </span>
      <% else %>
        <span class="player2">Player 2 deleted!</span>
      <% end %>

    <% elsif (match.game_type == "Doubles" && match.open == 0) %>
      
      <% if (User.find_by(id: match.player2) != nil) %>
        <span class="player2">Player 2: <%= User.find_by(id: match.player2).name %> </span>
      <% else %>
        <span class="player2">Player 2 deleted!</span>
      <% end %>
      
      <% if (User.find_by(id: match.player3) != nil) %>
        <span class="player3">Player 3: <%= User.find_by(id: match.player3).name %> </span>
      <% else %>
        <span class="player3">Player 3 deleted!</span>
      <% end %>

      <% if (User.find_by(id: match.player4) != nil) %>
        <span class="player4">Player 4: <%= User.find_by(id: match.player4).name %> </span>
      <% else %>
        <span class="player4">Player 4 deleted!</span>
      <% end %>

    <% elsif (match.game_type == "Singles" && match.open == 1 && match.player2 != 'Player 2' && User.find_by(id: match.player2) != nil) %>
      <span class="player2">Player 2: <%= User.find_by(id: match.player2).name %> </span>
    <% elsif (match.game_type == "Doubles" && match.open == 1) %>

      <% if (match.player2 != 'Player 2' && User.find_by(id: match.player2) != nil) %>
        <span class="player2">Player 2: <%= User.find_by(id: match.player2).name %></span>
      <% end %>

      <% if (match.player3 != 'Player 3' && User.find_by(id: match.player3) != nil) %>
        <span class="player3">Player 3: <%= User.find_by(id: match.player3).name %> </span>
      <% end %>

      <% if (match.player4 != 'Player 4' && User.find_by(id: match.player4) != nil) %>
        <span class="player4">Player 4: <%= User.find_by(id: match.player4).name %> </span>
      <% end %>

    <% end %> 
    
    <span class="time">Date and Time: <%= match.time.strftime("%x") %> at <%= match.time.strftime("%I:%M %p") %></span>

    <span class="location">Zip Code: <%= match.zip %></span>
    
    <span class="location">Location: <%= match.location %></span>
    
    <span class="game_type">Game Type: <%= match.game_type %></span>
    
    <% if (match.time < Time.now) %>
      <% if (match.score != nil) %>
        <span class="score">Score: <%= match.score %></span>
      <% end %>

      <% if (match.winner != nil) %>
        <span class="winner">Winner: <%= match.winner %></span>
      <% end %>

      <% if (match.loser != nil) %>
        <span class="loser">Loser: <%= match.loser %></span>
      <% end %>

    <% end %>

    <span class="timestamp">
      Created <%= time_ago_in_words(match.created_at) %> ago.
    </span>

    <% if ((match.p2Active == 0 && match.player2 == "#{current_user.id}") || (match.p3Active == 0 && match.player3 == "#{current_user.id}") || (match.p4Active == 0 && match.player4 == "#{current_user.id}")) %>
      <span> <%= link_to "Accept or Decline Challenge", match_path(match), class: "btn btn-success btn-block" %> </span>
    <% end %>

    <% if (match.game_type == 'Singles' && match.player2 == 'Player 2' && current_user != User.find_by(id: [match.player1]) && match.time > Time.now) %>
      <span> <%= link_to "Join Match", join_match_path(match), class: "btn btn-success btn-block" %> </span>
    <% end %>

    <% if (match.game_type == 'Doubles' && (match.player2 == 'Player 2' || match.player3 == 'Player 3' || match.player4 == 'Player 4') && current_user != User.find_by(id: [match.player1]) && current_user != User.find_by(id: [match.player2]) && current_user != User.find_by(id: [match.player3]) && current_user != User.find_by(id: [match.player4]) && match.time > Time.now) %>
      <span> <%= link_to "Join Match", join_match_path(match), class: "btn btn-success btn-block" %> </span>
    <% end %>

    <% if ((current_user == User.find_by(id: match.player1)) && match.time > Time.now) %>
      <span> <%= link_to "Delete Match", match, method: :delete,
                      class: "btn btn-block btn-danger", data: { confirm: "You sure?" } %> </span>
    <% end %>

      <% if (match.time < Time.now) && (current_user == User.find_by(id: match.player1) || current_user == User.find_by(id: match.player2) || current_user == User.find_by(id: match.player3) || current_user ==  User.find_by(id: match.player4)) %>
        <% if (match.game_type == "Singles" && match.player2 != 'Player 2') %> <%#Add in button checks  Change it for after validation %>
          <% if (match.scoreValid == 0) %>
            <span> <%= link_to "Enter match scores", edit_match_path(match), class: "btn btn-success btn-block" %> </span>
          <% elsif (match.scoreValid == 1 && match.validator1 == current_user.id) %>
            <span> <%= link_to "Validate match scores", edit_match_path(match), class: "btn btn-success btn-block" %> </span>
          <% end %>
        <% elsif (match.game_type == "Doubles" && match.player2 != 'Player 2' && match.player3 != 'Player 3' && match.player4 != 'Player 4') %> <%#Add in button checks.  Change it for after validation %>
          <% if (match.scoreValid == 0) %>
            <span> <%= link_to "Enter match scores", edit_match_path(match), class: "btn btn-success btn-block" %> </span>
          <% elsif (match.scoreValid == 1 && (match.validator1 == current_user.id || match.validator2 == current_user.id || match.validator3 == current_user.id)) %>
            <span> <%= link_to "Validate match scores", edit_match_path(match), class: "btn btn-success btn-block" %> </span>
          <% end %>
        <% end %>
      <% end %>

</li>

app/views/matches/challenges.html.erb
<% provide(:title, @user.name) %>

<div class="jumbotron">
	
  <div class="row">
	  <aside class="col-md-4">
	    <section>
	      <h1>
	        <%= gravatar_for @user %>
	        <%= @user.name %>
	      </h1>
	    </section>
	    <section class="stats">
	      <%= render 'users/follow_form' if logged_in? %>
	      <%= render 'shared/stats' %>
	    </section>
	    <section class="user_stats">
	      	<%= render 'users/user_stats' %>
	    </section>
	  </aside>
	  <div class="col-md-8">
	      <h3>Challenges</h3>
	      <ol class="matches">
	        <%= render @matches %>
	        <%#= render @deletedMatches %>
	      </ol>
	      <%= will_paginate @matches %>
	    	
	  </div>
	</div>
</div> 

app/views/matches/join.html.erb
<% provide(:title, "Join Match") %>

<div class="jumbotron center">

  <h1>Join Match</h1>
    <h2>Match Information</h2>

      <span class="player1">Player 1: <%= User.find_by(id: [@match.player1]).name %></span></br>

      <% if (@match.player2 != 'Player 2') %>
        <span class="player2">Player 2: <%= User.find_by(id: @match.player2).name %> </span></br>
      <% end %>

      <% if (@match.game_type == "Doubles") %>
        <% if (@match.player3 != 'Player 3') %>
          <span class="player3">Player 3: <%= User.find_by(id: @match.player3).name %> </span></br>
        <% end %>

        <% if (@match.player4 != 'Player 4') %>
          <span class="player4">Player 4: <%= User.find_by(id: @match.player4).name %> </span></br>
        <% end %>
      <% end %>

      <span class="time">Date and Time: <%= @match.time %></span></br>
      <span class="zip">Zip Code: <%=@match.zip %></span></br>
      <span class="location">Location: <%= @match.location %></span></br>
      <span class="game_type">Game Type: <%= @match.game_type %></span></br>

        <%if (@match.game_type == 'Singles' && @match.p2Active == 0 && @match.player1 != current_user.id)%>
          <%= form_for(@match) do |f| %>
            
          <%= f.hidden_field :player2, :value => current_user.id %>
          <%= f.hidden_field :p2Active, :value => 1 %>

          <div class = 'submit'>
            <%= f.submit "Join Match", class: "btn btn-primary btn-block" %>
          </div>
          <% end %>

        <% end %>

        <% if (@match.game_type == 'Doubles' && @match.player2 != current_user.id && @match.player3 != current_user.id && @match.player4 != current_user.id && (@match.p2Active == 0 || @match.p3Active == 0 || @match.p4Active == 0)) %>
          <%= form_for(@match) do |f| %>

          <% if (@match.player2 == 'Player 2') %>
            <%= f.label :player2, "I would like to join this match as the partner." %>
            <%= f.check_box :player2, { checked: false }, "#{@current_user.id}", 'Player 2'  %>
            <%#= f.hidden_field :p2Active, :value => 1 %>
          <% end %>

          <% if (@match.player3 == 'Player 3' || @match.player4 == 'Player 4') %>
            
            <% if (@match.player3 == 'Player 3') %>
              <%= f.label :player3, "I would like to join this match as an opponent." %>
              <%= f.check_box :player3, { checked: false }, "#{@current_user.id}", 'Player 3'  %>
              <%#= f.hidden_field :p3Active, :value => 1 %>

            <% elsif (@match.player4 == 'Player 4') %>
              <%= f.label :player4, "I would like to join this match as an opponent." %>
              <%= f.check_box :player4, { checked: false }, "#{@current_user.id}", 'Player 4'  %>
              <%#= f.hidden_field :p4Active, :value => 1 %>

            <% end %>

          <% end %>


        <div class = 'submit'>
          <%= f.submit "Submit", class: "btn btn-primary btn-block" %>
        </div>

        <% end %>

      <% end %> 

  </div>

app/views/matches/open.html.erb
<% provide(:title, "Open Matches") %>

<div class="jumbotron">

  <h1>Open Matches</h1>

  <div class="row">
    <div class="col-md-3 pull-left">
      <%= form_tag(open_path, :method => "get", id: "search-form") do %>
      <%= label :search1, "Find matches by type:" %>
      <%= select_tag(:search1, options_for_select(["Singles", "Doubles"]), :include_blank => true) %>
      <%#= text_field_tag :search1, params[:search1], placeholder: "Search Matches by Type"%>

      <%= label :search2, "Find matches by creator:" %>
      <%= text_field_tag :search2, params[:search2], placeholder: "Search Matches by User"%>

      <%= label :search3, "Find matches by zip:" %>
      <%= number_field_tag :search3, params[:search3], placeholder: "Search Matches by Zip"%>

      <%= label :search4, "Find matches by date:" %>
      <%= date_field_tag :search4, params[:search4], placeholder: "Search Matches by Date" %>

      <%= submit_tag "Search", :name => nil, class: "btn btn-success btn" %>
    <% end %>
    </div>

    <div class="center col-md-9">
      <ol class="matches">
          <%= render @matches %>
      </ol>
      <%= will_paginate @matches %>
    </div>

  </div>

</div>