config/routes.rb
Rails.application.routes.draw do
  #get 'password_resets/new'

  #get 'password_resets/edit'

  #get 'sessions/new'

  #get 'users/new'

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'new_match' => 'matches#new'

  get 'open' => 'matches#open'

  get 'challenges' => 'matches#challenges'


  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only:  [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :matches do
    member do
      get :join
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Zack Falgout </br>
    Master's Project</br>
    GameSetPlay.com</br>
    Committee: Dr. Susan Mengel (Chair) and Dr. Richard Watson
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://tennis.com">News</a></li>
    </ul>
  </nav>
    <div class = "center">
    <%= link_to image_tag("Tennis Court.JPG", alt: "Tennis Court", :size => "120x90"),
              'http://tennis.com/' %>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
      <div class="container">
             <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Black+Ops+One"><%= link_to "GAME! SET! PLAY!", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Help",   help_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li><%= link_to "View Open Matches", open_path %></li>
            <li class="divider"></li>
            <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

   <%= render 'layouts/header' %>
      <div class="container">
        <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
        <%= yield %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
      </div>
  </body>
</html>